### ISSUE TITLE
请问配置文件怎么修改

### ISSUE THREAD

**Issue by axh2018** [zqj2021/ImageWatermarket-0#1]
作者您好，我再在跑您这个项目的时候，不知道配置文件的这个1K，10K什么意思，能指点一下吗，谢谢！
train_cover_path = dataset_path + 'coco10K'
train_water_path = dataset_path + 'cifar10K'
test_cover_path = dataset_path + 'coco1K'
test_water_path = dataset_path + 'cifar1K'

**Comment by zqj2021** [comment]
你好 这些是训练集和测试集文件夹的路径
train_cover_path 表示训练集中图片文件夹的路径
train_water_path 表示训练集中水印文件夹的路径
coco1K 表示coco数据集中的1,000张图片
cifar10K 表示使用cifar的10,000张图片作为水印

**Comment by zqj2021** [comment]
你可以使用自己的训练集和测试集替换这些路径，只要保证文件夹中的所有内容都是图片就行
像  train_cover_path = "C://Datasets//训练集图片"

**Comment by axh2018** [comment]
谢谢！
